---
configure_terminal: false
configure_osx: true

configure_dock: true
dockitems_remove:
  - Mail
  - Calendar
  - Contacts
  - Reminders
  - Music
  - TV
  - Podcasts
dockitems_persist:
  - name: "Brave Browser"
    path: "/Applications/Brave Browser.app/"
    pos: 3
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
    pos: 5
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
    pos: 6
  - name: Remote Desktop Manager Free
    path: "/Applications/Remote Desktop Manager Free.app/"
    pos: 7
  - name: "iTerm"
    path: "/Applications/Iterm.app/"
    pos: 8
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 9

dotfiles_repo: "git@github-personal:Maddog2050/dotfiles.git"
dotfiles_repo_local_destination: ~/Development/dotfiles
dotfiles_files:
  - .gitconfig
  - .inputrc
  - .zshenv
  - .config/zsh/.aliases
  # - .config/zsh/.aliases.local
  - .config/zsh/.exports
  - .config/zsh/.exports.local
  - .config/zsh/.p10k.zsh
  - .config/zsh/.zshenv
  - .config/zsh/.zshrc
  - .oci/oci_api_key_public.pem
  - .oci/oci_api_key.pem
  - .ssh/config
  - .ssh/id_ansible
  - .ssh/id_ansible.pub
  - .ssh/id_github_personal
  - .ssh/id_github_personal.pub
  - .ssh/id_rsa
  - .ssh/id_rsa.pub
  # - .gitignore
  - .osx
  # - .vimrc

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - gcenx/wine
  - aws/tap
  - fluxcd/tap
  - buildpacks/tap

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - git
  - httpie
  - iperf
  - nmap
  - node
  - ssh-copy-id
  - readline
  - openssl
  - ca-certificates
  - wget
  - wrk
  # - zsh-history-substring-search
  # My Additions
  - aws-vault
  - awscli
  - docker-credential-helper-ecr
  - eksctl
  - git-remote-codecommit
  - jq
  - kubernetes-cli
  - terraform
  - terraform-docs
  - terragrunt
  - tflint
  # - winetricks
  - yq
  - helm
  - fluxcd/tap/flux
  - kustomize
  - packer
  - dive
  - sops
  - k9s
  # - serverless
  - tfsec
  - aws-nuke
  - driftctl
  - terrascan
  # - aws-sam-cli
  - act
  - kubescape
  # - talosctl # Not in homebrew
  - nvm
  # - gvm # Not in homebrew
  # - goenv # gvm alternative?
  - govc
  - krew
  # - kubeseal
  - ec2-instance-selector
  - buildpacks/tap/pack
  - webpack
  - dos2unix
  # - docker-credential-helpers
  - pyenv
  - pyenv-virtualenv
  - pyenv-pip-migrate

homebrew_upgrade_all_packages: true
homebrew_cask_apps:
  - docker
  # - firefox
  # - google-chrome
  # - transmit
  # - vagrant
  # My Additions
  - brave-browser
  - dbeaver-community
  - drawio
  - iterm2
  - keka
  - lens
  - p4v
  - remote-desktop-manager-free
  # - ringcentral
  - visual-studio-code
  - 1password
  - parallels
  - parallels-toolbox
  - forticlient-vpn
  # - wireshark
  # - rancher
  - microsoft-office
  - microsoft-teams
  - rectangle
  - browserosaurus
  # - teamviewer
  # - webex
  # - zoom
  # - amazon-chime
  # - postman
  # - name: wine-crossover
  #  install_options: 'no-quarantine,appdir={{ homebrew_cask_appdir }}'

mas_upgrade_all_apps: yes
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - name: 1Password for Safari  (2.3.7)
    id: 1569813296
  - name: Amphetamine
    id: 937984704

pip_packages:
  # My Additions
  - name: ansible
    state: latest
  - name: ansible-lint
    state: latest
  - name: molecule
    state: latest
  - name: molecule-docker
    state: latest
  - name: flake8
    state: latest
  - name: pep8-naming
    state: latest
  - name: black
    state: latest
  # - name: molecule-vagrant
  #   state: latest

vscode_install_extensions:
  - aaron-bond.better-comments
  - bierner.github-markdown-preview
  - eamodio.gitlens
  # - github.vscode-pull-request-github
  # - gitlab.gitlab-workflow
  - golang.go
  - gurumukhi.selected-lines-count
  - hashicorp.terraform
  - kevinrose.vsc-python-indent
  - mhutchie.git-graph
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  # - ms-vscode-remote.remote-wsl
  # - ms-vsliveshare.vsliveshare
  - redhat.ansible@0.11.29
  - redhat.vscode-yaml
  - rubymaniac.vscode-paste-and-indent
  - sebastianbille.iam-legend
  - streetsidesoftware.code-spell-checker
  - tyriar.sort-lines
  - wholroyd.jinja
  # Extensions in test
  - formulahendry.code-runner
  - njqdev.vscode-python-typehint
  - tabnine.tabnine-vscode
  - vscode-icons-team.vscode-icons

vscode_uninstall_extensions:
  - coenraads.bracket-pair-colorizer-2

pre_provision_tasks:
  - tasks/create-folders.yaml

post_provision_tasks:
  - tasks/vscode-settings.yml
  # - tasks/terraform-cloud.yml
  # - tasks/datadog.yml
  # - tasks/git-config.yml
  - tasks/aws-accounts.yml
  - tasks/docker-config.yml
  - tasks/helm-repos.yml

create_folders:
  - ~/.config
  - ~/.config/zsh
  - name: ~/.oci
    mode: '0700'
  - name: ~/.ssh
    mode: '0700'
  # Fix parallels
  # - name: /usr/local/share/man/man8
  #   mode: '0755'

terraform_cloud_token: '{{ vault_terraform_cloud_token }}'
datadog_api_key: '{{ vault_datadog_api_key }}'
datadog_app_key: '{{ vault_datadog_app_key }}'

user_email_address: 'stirka@cromwell.co.uk'
user_full_name: 'Adam Stirk'

aws_sso_start_url: 'https://cromwell.awsapps.com/start'
aws_sso_region: eu-west-1
aws_accounts:
  - name: 'Audit'
    profile_name: 'audit'
    account_id: '852949184558'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2C'
    profile_name: 'b2c'
    account_id: '589950153661'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2M - Development'
    profile_name: 'b2m-dev'
    account_id: '118861524496'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2M - Development - Dev'
    profile_name: 'b2m-dev-dev'
    account_id: '118861524496'
    role_name: 'CromwellITDevB2M_RW'
  - name: 'B2M - Old'
    profile_name: 'b2m-old'
    account_id: '991423240434'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2M - POC'
    profile_name: 'b2m-poc'
    account_id: '641929246019'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2M - POC - Dev'
    profile_name: 'b2m-poc-dev'
    account_id: '641929246019'
    role_name: 'CromwellITDevSandbox_Admin'
  - name: 'CromwellCloud'
    profile_name: 'cromwellcloud'
    account_id: '446508857870'
    role_name: 'AWSAdministratorAccess'
  - name: 'Log Archive'
    profile_name: 'log'
    account_id: '969777697084'
    role_name: 'AWSReadOnlyAccessManagement'
  - name: 'Networking'
    profile_name: 'networking'
    account_id: '612972968935'
    role_name: 'AWSAdministratorAccess'
  - name: 'Organization Master'
    profile_name: 'master'
    account_id: '465460000266'
    role_name: 'AWSAdministratorAccess'
  - name: 'Test'
    profile_name: 'test'
    account_id: '419886623144'
    role_name: 'AWSAdministratorAccess'
  - name: 'Supplier-EDI - Development'
    profile_name: 'supplier-edi-dev'
    account_id: '049965263356'
    role_name: 'AWSAdministratorAccess'
  - name: 'Supplier-EDI - Development - Dev'
    profile_name: 'supplier-edi-dev-dev'
    account_id: '049965263356'
    role_name: 'CromwellITDevSupplierEDI_RW'
  - name: 'Supplier-EDI - POC'
    profile_name: 'supplier-edi-poc'
    account_id: '322170495754'
    role_name: 'AWSAdministratorAccess'
  - name: 'Supplier-EDI - POC - Dev'
    profile_name: 'supplier-edi-poc-dev'
    account_id: '322170495754'
    role_name: 'CromwellITDevSandbox_Admin'
  - name: 'Shared-SFTP - Prod'
    profile_name: 'shared-sftp'
    account_id: '978341495299'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared-DB - Development'
    profile_name: 'shared-db-dev'
    account_id: '510493539625'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared-EmailService - Development'
    profile_name: 'shared-email-dev'
    account_id: '318177187255'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared-EmailService - Development - dev'
    profile_name: 'shared-email-dev-dev'
    account_id: '318177187255'
    role_name: 'CromwellITDevSharedEmail_RW'
  - name: 'Shared-DB - Staging'
    profile_name: 'shared-db-stg'
    account_id: '416410845083'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared-EmailService - Staging'
    profile_name: 'shared-email-stg'
    account_id: '427342695275'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2M - Staging'
    profile_name: 'b2m-stg'
    account_id: '444135266160'
    role_name: 'AWSAdministratorAccess'
  - name: 'B2M - Production'
    profile_name: 'b2m-prod'
    account_id: '671193358559'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared-DB - Production'
    profile_name: 'shared-db-prod'
    account_id: '253421281411'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared-EmailService - Production'
    profile_name: 'shared-email-prod'
    account_id: '474120604715'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared Merlin-API - Development'
    profile_name: 'merlin-api-dev'
    account_id: '415037428848'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared Merlin-API - Staging'
    profile_name: 'merlin-api-stg'
    account_id: '251330293003'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared Merlin-API - Production'
    profile_name: 'merlin-api-prod'
    account_id: '002391764475'
    role_name: 'AWSAdministratorAccess'
  - name: 'Supplier-EDI - Staging'
    profile_name: 'supplier-edi-stg'
    account_id: '776816033536'
    role_name: 'AWSAdministratorAccess'
  - name: 'Supplier-EDI - production'
    profile_name: 'supplier-edi-prod'
    account_id: '019012951475'
    role_name: 'AWSAdministratorAccess'
  - name: 'Shared Merlin-API - Development - Dev'
    profile_name: 'merlin-api-dev-dev'
    account_id: '415037428848'
    role_name: 'CromwellITDevMerlinAPI_RW'
  - name: 'Kubernetes - Development'
    profile_name: 'k8s-dev'
    account_id: '130792215552'
    role_name: 'AWSAdministratorAccess'
  - name: 'Kubernetes - Staging'
    profile_name: 'k8s-stg'
    account_id: '522075529659'
    role_name: 'AWSAdministratorAccess'
  - name: 'Kubernetes - Production'
    profile_name: 'k8s-prod'
    account_id: '060749347024'
    role_name: 'AWSAdministratorAccess'

helm_repos:
  - name: anchore
    repo_url: https://charts.anchore.io
  - name: armo
    repo_url: https://armosec.github.io/armo-helm/
  - name: csi-driver-nfs
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  - name: csi-driver-smb
    repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  - name: datadog
    repo_url: https://helm.datadoghq.com
  - name: eks
    repo_url: https://aws.github.io/eks-charts
  - name: grafana
    repo_url: https://grafana.github.io/helm-charts
  - name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    repo_url: https://charts.jetstack.io
  - name: k8s-gateway
    repo_url: https://ori-edge.github.io/k8s_gateway/
  - name: karpenter
    repo_url: https://charts.karpenter.sh
  - name: longhorn
    repo_url: https://charts.longhorn.io/
  - name: metrics-server
    repo_url: https://kubernetes-sigs.github.io/metrics-server/
  - name: nginx-stable
    repo_url: https://helm.nginx.com/stable
  - name: projectcalico
    repo_url: https://projectcalico.docs.tigera.io/charts
  - name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  - name: sealed-secrets
    repo_url: https://bitnami-labs.github.io/sealed-secrets
  - name: sops
    repo_url: https://isindir.github.io/sops-secrets-operator/
