---
- name: Configure Docker Daemon Config
  ansible.builtin.template:
    src: 'docker-daemon.json.j2'
    dest: '~/.docker/daemon.json'
    owner: '{{ ansible_user_id }}'
    mode: 0644
    directory_mode: 0755

- name: Configure Docker Config
  ansible.builtin.template:
    src: 'docker-config.json.j2'
    dest: '~/.docker/config.json'
    owner: '{{ ansible_user_id }}'
    mode: 0644
    directory_mode: 0755

- name: Configure Docker Features
  ansible.builtin.template:
    src: 'docker-features.json.j2'
    dest: '~/.docker/features.json'
    owner: '{{ ansible_user_id }}'
    mode: 0644
    directory_mode: 0755
