---
- name: VSCode Settings
  ansible.builtin.copy:
    src: vscode/settings.json
    dest: ~/Library/Application Support/Code/User/settings.json
    mode: 0o644
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Add/Remove VSCode Extensions
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: '{{ ansible_user_id }}'
        visual_studio_code_extensions: '{{ vscode_install_extensions | default(omit) }}'
        visual_studio_code_extensions_absent: '{{ vscode_uninstall_extensions | default(omit) }}'
